import type { NewAccount, NewCurrency } from "@accounting-kz/db";

// Base currency setup for Kazakhstan
export const baseCurrency: NewCurrency = {
	code: "KZT",
	name: "Kazakhstani Tenge",
	symbol: "₸",
	decimals: 2,
	isBaseCurrency: true,
	isActive: true,
};

export const additionalCurrencies: NewCurrency[] = [
	{
		code: "USD",
		name: "US Dollar",
		symbol: "$",
		decimals: 2,
		isBaseCurrency: false,
		isActive: true,
	},
	{
		code: "EUR",
		name: "Euro",
		symbol: "€",
		decimals: 2,
		isBaseCurrency: false,
		isActive: true,
	},
	{
		code: "RUB",
		name: "Russian Ruble",
		symbol: "₽",
		decimals: 2,
		isBaseCurrency: false,
		isActive: true,
	},
];

// Kazakhstan Chart of Accounts based on local standards
export const kazakhstanChartOfAccounts: (Omit<NewAccount, "parentId"> & {
	parentCode?: string;
})[] = [
	// ASSETS (1000-1999)
	{
		code: "1000",
		name: "ASSETS",
		accountType: "asset",
		description: "Total Assets",
		isActive: true,
	},

	// Current Assets (1100-1199)
	{
		code: "1100",
		name: "Current Assets",
		accountType: "asset",
		description: "Assets expected to be converted to cash within one year",
		parentCode: "1000",
		isActive: true,
	},
	{
		code: "1110",
		name: "Cash and Cash Equivalents",
		accountType: "asset",
		description: "Cash on hand and in banks",
		parentCode: "1100",
		isActive: true,
	},
	{
		code: "1111",
		name: "Petty Cash",
		accountType: "asset",
		description: "Small amounts of cash for minor expenses",
		parentCode: "1110",
		isActive: true,
	},
	{
		code: "1112",
		name: "Bank Account - KZT",
		accountType: "asset",
		description: "Primary bank account in Kazakhstani Tenge",
		parentCode: "1110",
		isActive: true,
	},
	{
		code: "1113",
		name: "Bank Account - USD",
		accountType: "asset",
		description: "Foreign currency bank account in US Dollars",
		parentCode: "1110",
		isActive: true,
	},
	{
		code: "1120",
		name: "Accounts Receivable",
		accountType: "asset",
		description: "Money owed by customers",
		parentCode: "1100",
		isActive: true,
	},
	{
		code: "1121",
		name: "Trade Receivables",
		accountType: "asset",
		description: "Amounts owed by customers for goods/services",
		parentCode: "1120",
		isActive: true,
	},
	{
		code: "1122",
		name: "Employee Advances",
		accountType: "asset",
		description: "Advances given to employees",
		parentCode: "1120",
		isActive: true,
	},
	{
		code: "1130",
		name: "Inventory",
		accountType: "asset",
		description: "Goods held for sale",
		parentCode: "1100",
		isActive: true,
	},

	// Non-Current Assets (1200-1299)
	{
		code: "1200",
		name: "Non-Current Assets",
		accountType: "asset",
		description: "Long-term assets",
		parentCode: "1000",
		isActive: true,
	},
	{
		code: "1210",
		name: "Property, Plant & Equipment",
		accountType: "asset",
		description: "Tangible fixed assets",
		parentCode: "1200",
		isActive: true,
	},
	{
		code: "1211",
		name: "Land",
		accountType: "asset",
		description: "Land owned by the company",
		parentCode: "1210",
		isActive: true,
	},
	{
		code: "1212",
		name: "Buildings",
		accountType: "asset",
		description: "Buildings and structures",
		parentCode: "1210",
		isActive: true,
	},
	{
		code: "1213",
		name: "Equipment",
		accountType: "asset",
		description: "Machinery and equipment",
		parentCode: "1210",
		isActive: true,
	},
	{
		code: "1220",
		name: "Intangible Assets",
		accountType: "asset",
		description: "Non-physical assets",
		parentCode: "1200",
		isActive: true,
	},
	{
		code: "1221",
		name: "Software",
		accountType: "asset",
		description: "Computer software and licenses",
		parentCode: "1220",
		isActive: true,
	},

	// LIABILITIES (2000-2999)
	{
		code: "2000",
		name: "LIABILITIES",
		accountType: "liability",
		description: "Total Liabilities",
		isActive: true,
	},

	// Current Liabilities (2100-2199)
	{
		code: "2100",
		name: "Current Liabilities",
		accountType: "liability",
		description: "Liabilities due within one year",
		parentCode: "2000",
		isActive: true,
	},
	{
		code: "2110",
		name: "Accounts Payable",
		accountType: "liability",
		description: "Money owed to suppliers",
		parentCode: "2100",
		isActive: true,
	},
	{
		code: "2111",
		name: "Trade Payables",
		accountType: "liability",
		description: "Amounts owed to suppliers for goods/services",
		parentCode: "2110",
		isActive: true,
	},
	{
		code: "2120",
		name: "Accrued Expenses",
		accountType: "liability",
		description: "Expenses incurred but not yet paid",
		parentCode: "2100",
		isActive: true,
	},
	{
		code: "2130",
		name: "Taxes Payable",
		accountType: "liability",
		description: "Taxes owed to government",
		parentCode: "2100",
		isActive: true,
	},
	{
		code: "2131",
		name: "VAT Payable",
		accountType: "liability",
		description: "Value Added Tax owed",
		parentCode: "2130",
		isActive: true,
	},
	{
		code: "2132",
		name: "Income Tax Payable",
		accountType: "liability",
		description: "Corporate income tax owed",
		parentCode: "2130",
		isActive: true,
	},

	// Non-Current Liabilities (2200-2299)
	{
		code: "2200",
		name: "Non-Current Liabilities",
		accountType: "liability",
		description: "Long-term liabilities",
		parentCode: "2000",
		isActive: true,
	},
	{
		code: "2210",
		name: "Long-term Debt",
		accountType: "liability",
		description: "Debt payable over more than one year",
		parentCode: "2200",
		isActive: true,
	},

	// EQUITY (3000-3999)
	{
		code: "3000",
		name: "EQUITY",
		accountType: "equity",
		description: "Owner's Equity",
		isActive: true,
	},
	{
		code: "3100",
		name: "Share Capital",
		accountType: "equity",
		description: "Capital invested by shareholders",
		parentCode: "3000",
		isActive: true,
	},
	{
		code: "3200",
		name: "Retained Earnings",
		accountType: "equity",
		description: "Accumulated profits retained in business",
		parentCode: "3000",
		isActive: true,
	},

	// REVENUE (4000-4999)
	{
		code: "4000",
		name: "REVENUE",
		accountType: "revenue",
		description: "Total Revenue",
		isActive: true,
	},
	{
		code: "4100",
		name: "Operating Revenue",
		accountType: "revenue",
		description: "Revenue from main business activities",
		parentCode: "4000",
		isActive: true,
	},
	{
		code: "4110",
		name: "Sales Revenue",
		accountType: "revenue",
		description: "Revenue from sales of goods/services",
		parentCode: "4100",
		isActive: true,
	},
	{
		code: "4200",
		name: "Other Revenue",
		accountType: "revenue",
		description: "Non-operating revenue",
		parentCode: "4000",
		isActive: true,
	},
	{
		code: "4210",
		name: "Interest Income",
		accountType: "revenue",
		description: "Income from interest on deposits",
		parentCode: "4200",
		isActive: true,
	},

	// EXPENSES (5000-9999)
	{
		code: "5000",
		name: "EXPENSES",
		accountType: "expense",
		description: "Total Expenses",
		isActive: true,
	},
	{
		code: "5100",
		name: "Cost of Goods Sold",
		accountType: "expense",
		description: "Direct costs of producing goods sold",
		parentCode: "5000",
		isActive: true,
	},
	{
		code: "6000",
		name: "Operating Expenses",
		accountType: "expense",
		description: "Expenses from regular business operations",
		parentCode: "5000",
		isActive: true,
	},
	{
		code: "6100",
		name: "Administrative Expenses",
		accountType: "expense",
		description: "General administrative costs",
		parentCode: "6000",
		isActive: true,
	},
	{
		code: "6110",
		name: "Salaries and Wages",
		accountType: "expense",
		description: "Employee compensation",
		parentCode: "6100",
		isActive: true,
	},
	{
		code: "6120",
		name: "Office Supplies",
		accountType: "expense",
		description: "Office supplies and materials",
		parentCode: "6100",
		isActive: true,
	},
	{
		code: "6130",
		name: "Utilities",
		accountType: "expense",
		description: "Electricity, water, gas, internet",
		parentCode: "6100",
		isActive: true,
	},
	{
		code: "6140",
		name: "Rent Expense",
		accountType: "expense",
		description: "Office rent payments",
		parentCode: "6100",
		isActive: true,
	},
	{
		code: "7000",
		name: "Financial Expenses",
		accountType: "expense",
		description: "Interest and financial costs",
		parentCode: "5000",
		isActive: true,
	},
	{
		code: "7100",
		name: "Interest Expense",
		accountType: "expense",
		description: "Interest paid on loans and debt",
		parentCode: "7000",
		isActive: true,
	},
];
