import type { NewAccount, NewCurrency } from "@accounting-kz/db";

// Base currency setup for Kazakhstan
export const baseCurrency: NewCurrency = {
	code: "KZT",
	name: "Kazakhstani Tenge",
	symbol: "₸",
	decimals: 2,
	isBaseCurrency: true,
	isActive: true,
};

export const additionalCurrencies: NewCurrency[] = [
	{
		code: "USD",
		name: "US Dollar",
		symbol: "$",
		decimals: 2,
		isBaseCurrency: false,
		isActive: true,
	},
	{
		code: "EUR",
		name: "Euro",
		symbol: "€",
		decimals: 2,
		isBaseCurrency: false,
		isActive: true,
	},
	{
		code: "RUB",
		name: "Russian Ruble",
		symbol: "₽",
		decimals: 2,
		isBaseCurrency: false,
		isActive: true,
	},
];

// Kazakhstan Chart of Accounts based on official local standards
export const kazakhstanChartOfAccounts: (Omit<NewAccount, "parentId" | "legalEntityId"> & {
	parentCode?: string;
})[] = [
		// CASH AND CASH EQUIVALENTS (1010-1090)
		{
			code: "1010",
			name: "Денежные средства в кассе",
			accountType: "asset",
			description: "Cash on hand",
			isActive: true,
		},
		{
			code: "1030",
			name: "Денежные средства на текущих банковских счетах",
			accountType: "asset",
			description: "Money in current bank accounts",
			isActive: true,
		},
		{
			code: "1050",
			name: "Денежные средства на сберегательных счетах",
			accountType: "asset",
			description: "Money in savings accounts",
			isActive: true,
		},

		// SHORT-TERM RECEIVABLES (1210-1280)
		{
			code: "1210",
			name: "Краткосрочная дебиторская задолженность покупателей и заказчиков",
			accountType: "asset",
			description: "Short-term receivables from buyers and customers",
			isActive: true,
		},
		{
			code: "1251",
			name: "Краткосрочная задолженность подотчетных лиц",
			accountType: "asset",
			description: "Short-term advances to accountable persons",
			isActive: true,
		},
		{
			code: "1280",
			name: "Оценочный резерв под убытки от обесценения краткосрочной дебиторской задолженности",
			accountType: "asset",
			description: "Provision for impairment of short-term receivables",
			isActive: true,
		},

		// INVENTORY (1310-1370)
		{
			code: "1310",
			name: "Сырье и материалы",
			accountType: "asset",
			description: "Raw materials and supplies",
			isActive: true,
		},
		{
			code: "1320",
			name: "Готовая продукция",
			accountType: "asset",
			description: "Finished goods",
			isActive: true,
		},
		{
			code: "1330",
			name: "Товары",
			accountType: "asset",
			description: "Merchandise inventory",
			isActive: true,
		},

		// TAX ASSETS (1410-1430)
		{
			code: "1421",
			name: "Налог на добавленную стоимость к возмещению",
			accountType: "asset",
			description: "VAT recoverable",
			isActive: true,
		},

		// LONG-TERM RECEIVABLES (2110-2180)
		{
			code: "2110",
			name: "Долгосрочная задолженность покупателей и заказчиков",
			accountType: "asset",
			description: "Long-term receivables from buyers and customers",
			isActive: true,
		},

		// FIXED ASSETS (2410-2460)
		{
			code: "2410",
			name: "Основные средства",
			accountType: "asset",
			description: "Property, plant and equipment",
			isActive: true,
		},
		{
			code: "2420",
			name: "Амортизация основных средств",
			accountType: "asset",
			description: "Accumulated depreciation of PPE",
			isActive: true,
		},

		// INTANGIBLE ASSETS (2710-2780)
		{
			code: "2730",
			name: "Прочие нематериальные активы",
			accountType: "asset",
			description: "Other intangible assets",
			isActive: true,
		},
		{
			code: "2740",
			name: "Амортизация прочих нематериальных активов",
			accountType: "asset",
			description: "Accumulated amortization of intangible assets",
			isActive: true,
		},

		// SHORT-TERM FINANCIAL LIABILITIES (3010-3080)
		{
			code: "3010",
			name: "Краткосрочные финансовые обязательства, оцениваемые по амортизированной стоимости",
			accountType: "liability",
			description: "Short-term financial liabilities at amortized cost",
			isActive: true,
		},

		// TAX LIABILITIES (3110-3190)
		{
			code: "3110",
			name: "Корпоративный подоходный налог подлежащий уплате",
			accountType: "liability",
			description: "Corporate income tax payable",
			isActive: true,
		},
		{
			code: "3120",
			name: "Индивидуальный подоходный налог",
			accountType: "liability",
			description: "Individual income tax payable",
			isActive: true,
		},
		{
			code: "3130",
			name: "Налог на добавленную стоимость",
			accountType: "liability",
			description: "VAT payable",
			isActive: true,
		},
		{
			code: "3190",
			name: "Прочие налоги",
			accountType: "liability",
			description: "Other taxes payable",
			isActive: true,
		},

		// SOCIAL CONTRIBUTIONS (3211-3240)
		{
			code: "3211",
			name: "Обязательства по социальным отчислениям",
			accountType: "liability",
			description: "Social contribution obligations",
			isActive: true,
		},
		{
			code: "3220",
			name: "Обязательства по пенсионным отчислениям",
			accountType: "liability",
			description: "Pension contribution obligations",
			isActive: true,
		},

		// TRADE PAYABLES (3310-3387)
		{
			code: "3310",
			name: "Краткосрочная задолженность поставщикам и подрядчикам",
			accountType: "liability",
			description: "Short-term payables to suppliers and contractors",
			isActive: true,
		},
		{
			code: "3350",
			name: "Краткосрочная задолженность по оплате труда",
			accountType: "liability",
			description: "Short-term payroll liabilities",
			isActive: true,
		},

		// LONG-TERM FINANCIAL LIABILITIES (4010-4060)
		{
			code: "4010",
			name: "Долгосрочные финансовые обязательства, оцениваемые по амортизированной стоимости",
			accountType: "liability",
			description: "Long-term financial liabilities at amortized cost",
			isActive: true,
		},

		// EQUITY (5010-5710)
		{
			code: "5010",
			name: "Простые акции",
			accountType: "equity",
			description: "Common shares",
			isActive: true,
		},
		{
			code: "5610",
			name: "Нераспределенная прибыль непокрытый убыток отчетного года",
			accountType: "equity",
			description: "Retained earnings/accumulated loss for current year",
			isActive: true,
		},
		{
			code: "5620",
			name: "Нераспределенная прибыль непокрытый убыток предыдущих лет",
			accountType: "equity",
			description: "Retained earnings/accumulated loss from previous years",
			isActive: true,
		},

		// REVENUE (6010-6420)
		{
			code: "6010",
			name: "Доход от реализации продукции и оказания услуг",
			accountType: "revenue",
			description: "Revenue from sale of products and services",
			isActive: true,
		},
		{
			code: "6110",
			name: "Доходы по вознаграждениям",
			accountType: "revenue",
			description: "Interest income",
			isActive: true,
		},
		{
			code: "6210",
			name: "Доходы от выбытия активов",
			accountType: "revenue",
			description: "Gains on disposal of assets",
			isActive: true,
		},
		{
			code: "6290",
			name: "Прочие доходы",
			accountType: "revenue",
			description: "Other income",
			isActive: true,
		},

		// EXPENSES (7010-7710)
		{
			code: "7010",
			name: "Себестоимость реализованной продукции и оказанных услуг",
			accountType: "expense",
			description: "Cost of goods sold and services rendered",
			isActive: true,
		},
		{
			code: "7110",
			name: "Расходы по реализации продукции и оказанию услуг",
			accountType: "expense",
			description: "Selling expenses",
			isActive: true,
		},
		{
			code: "7210",
			name: "Административные расходы",
			accountType: "expense",
			description: "Administrative expenses",
			isActive: true,
		},
		{
			code: "7310",
			name: "Расходы по вознаграждениям",
			accountType: "expense",
			description: "Interest expenses",
			isActive: true,
		},
		{
			code: "7410",
			name: "Расходы по выбытию активов",
			accountType: "expense",
			description: "Losses on disposal of assets",
			isActive: true,
		},
		{
			code: "7480",
			name: "Прочие расходы",
			accountType: "expense",
			description: "Other expenses",
			isActive: true,
		},
		{
			code: "7710",
			name: "Расходы по корпоративному подоходному налогу",
			accountType: "expense",
			description: "Corporate income tax expense",
			isActive: true,
		},

		// PRODUCTION ACCOUNTS (8110-8410)
		{
			code: "8110",
			name: "Основное производство",
			accountType: "expense",
			description: "Main production",
			isActive: true,
		},
		{
			code: "1021",
			name: "Денежные средства в пути",
			accountType: "asset",
			description: "Денежные средства в пути",
			isActive: true,
		},
		{
			code: "1022",
			name: "Конвертация валюты",
			accountType: "asset",
			description: "Конвертация валюты",
			isActive: true,
		},
		{
			code: "1040",
			name: "Денежные средства на корреспондентских счетах",
			accountType: "asset",
			description: "Денежные средства на корреспондентских счетах",
			isActive: true,
		},
		{
			code: "1060",
			name: "Денежные средства ограниченные в использовании",
			accountType: "asset",
			description: "Денежные средства ограниченные в использовании",
			isActive: true,
		},
		{
			code: "1070",
			name: "Учет электронных денежных средств",
			accountType: "asset",
			description: "Учет электронных денежных средств",
			isActive: true,
		},
		{
			code: "1080",
			name: "Прочие денежные средства",
			accountType: "asset",
			description: "Прочие денежные средства",
			isActive: true,
		},
		{
			code: "1090",
			name: "Оценочный резерв под убытки от обесценения денежных средств",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения денежных средств",
			isActive: true,
		},
		{
			code: "1110",
			name: "Краткосрочные финансовые активы оцениваемые по амортизированной стоимости",
			accountType: "asset",
			description: "Краткосрочные финансовые активы оцениваемые по амортизированной стоимости",
			isActive: true,
		},
		{
			code: "1120",
			name: "Краткосрочные финансовые активы оцениваемые по справедливой стоимости через прочий совокупный доход",
			accountType: "asset",
			description: "Краткосрочные финансовые активы оцениваемые по справедливой стоимости через прочий совокупный доход",
			isActive: true,
		},
		{
			code: "1130",
			name: "Краткосрочные финансовые активы оцениваемые по справедливой стоимости через прибыль или убыток",
			accountType: "asset",
			description: "Краткосрочные финансовые активы оцениваемые по справедливой стоимости через прибыль или убыток",
			isActive: true,
		},
		{
			code: "1140",
			name: "Производные финансовые инструменты",
			accountType: "asset",
			description: "Производные финансовые инструменты",
			isActive: true,
		},
		{
			code: "1151",
			name: "Краткосрочные вознаграждения к получению по предоставленным займам контрагентам",
			accountType: "asset",
			description: "Краткосрочные вознаграждения к получению по предоставленным займам контрагентам",
			isActive: true,
		},
		{
			code: "1152",
			name: "Краткосрочные вознаграждения к получению по предоставленным займам работникам",
			accountType: "asset",
			description: "Краткосрочные вознаграждения к получению по предоставленным займам работникам",
			isActive: true,
		},
		{
			code: "1160",
			name: "Прочие краткосрочные финансовые активы",
			accountType: "asset",
			description: "Прочие краткосрочные финансовые активы",
			isActive: true,
		},
		{
			code: "1170",
			name: "Оценочный резерв под убытки от обесценения краткосрочных финансовых активов",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения краткосрочных финансовых активов",
			isActive: true,
		},
		{
			code: "1220",
			name: "Краткосрочная дебиторская задолженность дочерних организаций",
			accountType: "asset",
			description: "Краткосрочная дебиторская задолженность дочерних организаций",
			isActive: true,
		},
		{
			code: "1230",
			name: "Краткосрочная дебиторская задолженность ассоциированных и совместных организаций",
			accountType: "asset",
			description: "Краткосрочная дебиторская задолженность ассоциированных и совместных организаций",
			isActive: true,
		},
		{
			code: "1240",
			name: "Краткосрочная дебиторская задолженность филиалов и структурных подразделений",
			accountType: "asset",
			description: "Краткосрочная дебиторская задолженность филиалов и структурных подразделений",
			isActive: true,
		},
		{
			code: "1252",
			name: "Задолженность по выплаченной заработной плате",
			accountType: "asset",
			description: "Задолженность по выплаченной заработной плате",
			isActive: true,
		},
		{
			code: "1253",
			name: "Краткосрочная задолженность по предоставленным работникам займам",
			accountType: "asset",
			description: "Краткосрочная задолженность по предоставленным работникам займам",
			isActive: true,
		},
		{
			code: "1254",
			name: "Прочая краткосрочная задолженность работников (хищение порча материальный ущерб и др.)",
			accountType: "asset",
			description: "Прочая краткосрочная задолженность работников (хищение порча материальный ущерб и др.)",
			isActive: true,
		},
		{
			code: "1260",
			name: "Краткосрочная дебиторская задолженность по аренде",
			accountType: "asset",
			description: "Краткосрочная дебиторская задолженность по аренде",
			isActive: true,
		},
		{
			code: "1271",
			name: "Задолженность по возвратам ТМЗ поставщикам",
			accountType: "asset",
			description: "Задолженность по возвратам ТМЗ поставщикам",
			isActive: true,
		},
		{
			code: "1272",
			name: "Задолженность по претензиям",
			accountType: "asset",
			description: "Задолженность по претензиям",
			isActive: true,
		},
		{
			code: "1273",
			name: "Задолженность по выявленным недостачам ТМЗ",
			accountType: "asset",
			description: "Задолженность по выявленным недостачам ТМЗ",
			isActive: true,
		},
		{
			code: "1274",
			name: "Прочая краткосрочная дебиторская задолженность",
			accountType: "asset",
			description: "Прочая краткосрочная дебиторская задолженность",
			isActive: true,
		},
		{
			code: "1341",
			name: "Основное производство",
			accountType: "asset",
			description: "Основное производство",
			isActive: true,
		},
		{
			code: "1342",
			name: "Полуфабрикаты собственного производства",
			accountType: "asset",
			description: "Полуфабрикаты собственного производства",
			isActive: true,
		},
		{
			code: "1343",
			name: "Вспомогательные производства",
			accountType: "asset",
			description: "Вспомогательные производства",
			isActive: true,
		},
		{
			code: "1351",
			name: "Материалы переданные в переработку",
			accountType: "asset",
			description: "Материалы переданные в переработку",
			isActive: true,
		},
		{
			code: "1361",
			name: "Резерв по списанию сырья и материалов",
			accountType: "asset",
			description: "Резерв по списанию сырья и материалов",
			isActive: true,
		},
		{
			code: "1362",
			name: "Резерв по списанию готовой продукции",
			accountType: "asset",
			description: "Резерв по списанию готовой продукции",
			isActive: true,
		},
		{
			code: "1363",
			name: "Резерв по списанию товаров",
			accountType: "asset",
			description: "Резерв по списанию товаров",
			isActive: true,
		},
		{
			code: "1370",
			name: "Актив по праву на возврат запасов",
			accountType: "asset",
			description: "Актив по праву на возврат запасов",
			isActive: true,
		},
		{
			code: "1410",
			name: "Корпоративный подоходный налог",
			accountType: "asset",
			description: "Корпоративный подоходный налог",
			isActive: true,
		},
		{
			code: "1422",
			name: "Налог на добавленную стоимость (отложенное принятие к зачету)",
			accountType: "asset",
			description: "Налог на добавленную стоимость (отложенное принятие к зачету)",
			isActive: true,
		},
		{
			code: "1423",
			name: "НДС уплачиваемый налоговым агентом",
			accountType: "asset",
			description: "НДС уплачиваемый налоговым агентом",
			isActive: true,
		},
		{
			code: "1424",
			name: "Излишне уплаченные в бюджет суммы НДС",
			accountType: "asset",
			description: "Излишне уплаченные в бюджет суммы НДС",
			isActive: true,
		},
		{
			code: "1430",
			name: "Прочие налоги и другие обязательные платежи в бюджет",
			accountType: "asset",
			description: "Прочие налоги и другие обязательные платежи в бюджет",
			isActive: true,
		},
		{
			code: "1510",
			name: "Долгосрочные активы предназначенные для продажи",
			accountType: "asset",
			description: "Долгосрочные активы предназначенные для продажи",
			isActive: true,
		},
		{
			code: "1520",
			name: "Группы на выбытие предназначенные для продажи",
			accountType: "asset",
			description: "Группы на выбытие предназначенные для продажи",
			isActive: true,
		},
		{
			code: "1530",
			name: "Оценочный резерв под убытки от обесценения долгосрочных активов (или выбывающих групп) предназначенных для продажи",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения долгосрочных активов (или выбывающих групп) предназначенных для продажи",
			isActive: true,
		},
		{
			code: "1610",
			name: "Растения",
			accountType: "asset",
			description: "Растения",
			isActive: true,
		},
		{
			code: "1620",
			name: "Животные",
			accountType: "asset",
			description: "Животные",
			isActive: true,
		},
		{
			code: "1630",
			name: "Оценочный резерв под убытки от обесценения биологических активов",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения биологических активов",
			isActive: true,
		},
		{
			code: "1710",
			name: "Краткосрочные авансы выданные",
			accountType: "asset",
			description: "Краткосрочные авансы выданные",
			isActive: true,
		},
		{
			code: "1720",
			name: "Расходы будущих периодов",
			accountType: "asset",
			description: "Расходы будущих периодов",
			isActive: true,
		},
		{
			code: "1730",
			name: "Краткосрочные активы по договорам",
			accountType: "asset",
			description: "Краткосрочные активы по договорам",
			isActive: true,
		},
		{
			code: "1740",
			name: "Оценочный резерв под убытки от обесценения краткосрочных активов по договорам",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения краткосрочных активов по договорам",
			isActive: true,
		},
		{
			code: "1750",
			name: "Прочие краткосрочные активы",
			accountType: "asset",
			description: "Прочие краткосрочные активы",
			isActive: true,
		},
		{
			code: "2010",
			name: "Долгосрочные финансовые активы оцениваемые по амортизированной стоимости",
			accountType: "asset",
			description: "Долгосрочные финансовые активы оцениваемые по амортизированной стоимости",
			isActive: true,
		},
		{
			code: "2020",
			name: "Долгосрочные финансовые активы оцениваемые по справедливой стоимости через прочий совокупный доход",
			accountType: "asset",
			description: "Долгосрочные финансовые активы оцениваемые по справедливой стоимости через прочий совокупный доход",
			isActive: true,
		},
		{
			code: "2030",
			name: "Долгосрочные финансовые активы оцениваемые по справедливой стоимости через прибыль или убыток",
			accountType: "asset",
			description: "Долгосрочные финансовые активы оцениваемые по справедливой стоимости через прибыль или убыток",
			isActive: true,
		},
		{
			code: "2040",
			name: "Производные финансовые инструменты",
			accountType: "asset",
			description: "Производные финансовые инструменты",
			isActive: true,
		},
		{
			code: "2050",
			name: "Долгосрочные вознаграждения к получению",
			accountType: "asset",
			description: "Долгосрочные вознаграждения к получению",
			isActive: true,
		},
		{
			code: "2060",
			name: "Долевые инструменты",
			accountType: "asset",
			description: "Долевые инструменты",
			isActive: true,
		},
		{
			code: "2070",
			name: "Прочие долгосрочные финансовые активы",
			accountType: "asset",
			description: "Прочие долгосрочные финансовые активы",
			isActive: true,
		},
		{
			code: "2080",
			name: "Оценочный резерв под убытки от обесценения долгосрочных финансовых активов",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения долгосрочных финансовых активов",
			isActive: true,
		},
		{
			code: "2120",
			name: "Долгосрочная дебиторская задолженность дочерних организаций",
			accountType: "asset",
			description: "Долгосрочная дебиторская задолженность дочерних организаций",
			isActive: true,
		},
		{
			code: "2130",
			name: "Долгосрочная дебиторская задолженность ассоциированных и совместных организаций",
			accountType: "asset",
			description: "Долгосрочная дебиторская задолженность ассоциированных и совместных организаций",
			isActive: true,
		},
		{
			code: "2140",
			name: "Долгосрочная дебиторская задолженность филиалов и структурных подразделений",
			accountType: "asset",
			description: "Долгосрочная дебиторская задолженность филиалов и структурных подразделений",
			isActive: true,
		},
		{
			code: "2151",
			name: "Задолженность подотчетных лиц",
			accountType: "asset",
			description: "Задолженность подотчетных лиц",
			isActive: true,
		},
		{
			code: "2152",
			name: "Задолженность по выплаченной заработной плате",
			accountType: "asset",
			description: "Задолженность по выплаченной заработной плате",
			isActive: true,
		},
		{
			code: "2153",
			name: "Долгосрочная задолженность по предоставленным работникам займам",
			accountType: "asset",
			description: "Долгосрочная задолженность по предоставленным работникам займам",
			isActive: true,
		},
		{
			code: "2154",
			name: "Прочая долгосрочная задолженность работников (хищение порча материальный ущерб и др.)",
			accountType: "asset",
			description: "Прочая долгосрочная задолженность работников (хищение порча материальный ущерб и др.)",
			isActive: true,
		},
		{
			code: "2160",
			name: "Долгосрочная дебиторская задолженность по аренде",
			accountType: "asset",
			description: "Долгосрочная дебиторская задолженность по аренде",
			isActive: true,
		},
		{
			code: "2171",
			name: "Задолженность по возвратам ТМЗ поставщикам",
			accountType: "asset",
			description: "Задолженность по возвратам ТМЗ поставщикам",
			isActive: true,
		},
		{
			code: "2172",
			name: "Долгосрочная задолженность по претензиям",
			accountType: "asset",
			description: "Долгосрочная задолженность по претензиям",
			isActive: true,
		},
		{
			code: "2173",
			name: "Задолженность по выявленным недостачам ТМЗ",
			accountType: "asset",
			description: "Задолженность по выявленным недостачам ТМЗ",
			isActive: true,
		},
		{
			code: "2174",
			name: "Прочая долгосрочная дебиторская задолженность",
			accountType: "asset",
			description: "Прочая долгосрочная дебиторская задолженность",
			isActive: true,
		},
		{
			code: "2180",
			name: "Оценочный резерв под убытки от обесценения долгосрочной дебиторской задолженности",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения долгосрочной дебиторской задолженности",
			isActive: true,
		},
		{
			code: "2210",
			name: "Инвестиции учитываемые методом долевого участия",
			accountType: "asset",
			description: "Инвестиции учитываемые методом долевого участия",
			isActive: true,
		},
		{
			code: "2220",
			name: "Инвестиции учитываемые по первоначальной стоимости",
			accountType: "asset",
			description: "Инвестиции учитываемые по первоначальной стоимости",
			isActive: true,
		},
		{
			code: "2230",
			name: "Оценочный резерв под убытки от обесценения инвестиций",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения инвестиций",
			isActive: true,
		},
		{
			code: "2310",
			name: "Инвестиционное имущество",
			accountType: "asset",
			description: "Инвестиционное имущество",
			isActive: true,
		},
		{
			code: "2320",
			name: "Амортизация инвестиционного имущества",
			accountType: "asset",
			description: "Амортизация инвестиционного имущества",
			isActive: true,
		},
		{
			code: "2330",
			name: "Оценочный резерв под убытки от обесценения инвестиционного имущества",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения инвестиционного имущества",
			isActive: true,
		},
		{
			code: "2430",
			name: "Оценочный резерв под убытки от обесценения основных средств",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения основных средств",
			isActive: true,
		},
		{
			code: "2440",
			name: "Право пользования активом",
			accountType: "asset",
			description: "Право пользования активом",
			isActive: true,
		},
		{
			code: "2450",
			name: "Амортизация права пользования активом",
			accountType: "asset",
			description: "Амортизация права пользования активом",
			isActive: true,
		},
		{
			code: "2460",
			name: "Оценочный резерв под убытки от обесценения права пользования активом",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения права пользования активом",
			isActive: true,
		},
		{
			code: "2510",
			name: "Растения",
			accountType: "asset",
			description: "Растения",
			isActive: true,
		},
		{
			code: "2520",
			name: "Животные",
			accountType: "asset",
			description: "Животные",
			isActive: true,
		},
		{
			code: "2530",
			name: "Амортизация биологических активов",
			accountType: "asset",
			description: "Амортизация биологических активов",
			isActive: true,
		},
		{
			code: "2540",
			name: "Оценочный резерв под убытки от обесценения биологических активов",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения биологических активов",
			isActive: true,
		},
		{
			code: "2610",
			name: "Разведочные и оценочные активы",
			accountType: "asset",
			description: "Разведочные и оценочные активы",
			isActive: true,
		},
		{
			code: "2620",
			name: "Амортизация разведочных и оценочных активов",
			accountType: "asset",
			description: "Амортизация разведочных и оценочных активов",
			isActive: true,
		},
		{
			code: "2630",
			name: "Оценочный резерв под убытки от обесценения разведочных и оценочных активов",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения разведочных и оценочных активов",
			isActive: true,
		},
		{
			code: "2710",
			name: "Гудвилл",
			accountType: "asset",
			description: "Гудвилл",
			isActive: true,
		},
		{
			code: "2720",
			name: "Обесценение гудвилла",
			accountType: "asset",
			description: "Обесценение гудвилла",
			isActive: true,
		},
		{
			code: "2750",
			name: "Оценочный резерв под убытки от обесценения прочих нематериальных активов",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения прочих нематериальных активов",
			isActive: true,
		},
		{
			code: "2760",
			name: "Право пользования активом",
			accountType: "asset",
			description: "Право пользования активом",
			isActive: true,
		},
		{
			code: "2770",
			name: "Амортизация права пользования активом",
			accountType: "asset",
			description: "Амортизация права пользования активом",
			isActive: true,
		},
		{
			code: "2780",
			name: "Оценочный резерв под убытки от обесценения права пользования активом",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения права пользования активом",
			isActive: true,
		},
		{
			code: "2810",
			name: "Отложенные налоговые активы по корпоративному подоходному налогу",
			accountType: "asset",
			description: "Отложенные налоговые активы по корпоративному подоходному налогу",
			isActive: true,
		},
		{
			code: "2910",
			name: "Долгосрочные авансы выданные",
			accountType: "asset",
			description: "Долгосрочные авансы выданные",
			isActive: true,
		},
		{
			code: "2920",
			name: "Расходы будущих периодов",
			accountType: "asset",
			description: "Расходы будущих периодов",
			isActive: true,
		},
		{
			code: "2931",
			name: "Незавершенное строительство",
			accountType: "asset",
			description: "Незавершенное строительство",
			isActive: true,
		},
		{
			code: "2932",
			name: "Монтаж оборудования",
			accountType: "asset",
			description: "Монтаж оборудования",
			isActive: true,
		},
		{
			code: "2933",
			name: "Модернизация и капитальный ремонт ОС",
			accountType: "asset",
			description: "Модернизация и капитальный ремонт ОС",
			isActive: true,
		},
		{
			code: "2940",
			name: "Долгосрочные активы по договорам",
			accountType: "asset",
			description: "Долгосрочные активы по договорам",
			isActive: true,
		},
		{
			code: "2950",
			name: "Оценочный резерв под убытки от обесценения долгосрочных активов по договорам",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения долгосрочных активов по договорам",
			isActive: true,
		},
		{
			code: "2960",
			name: "Затраты по договорам",
			accountType: "asset",
			description: "Затраты по договорам",
			isActive: true,
		},
		{
			code: "2970",
			name: "Амортизация затрат по договорам",
			accountType: "asset",
			description: "Амортизация затрат по договорам",
			isActive: true,
		},
		{
			code: "2980",
			name: "Оценочный резерв под убытки от обесценения затрат по договорам",
			accountType: "asset",
			description: "Оценочный резерв под убытки от обесценения затрат по договорам",
			isActive: true,
		},
		{
			code: "2990",
			name: "Прочие долгосрочные активы",
			accountType: "asset",
			description: "Прочие долгосрочные активы",
			isActive: true,
		},
		{
			code: "3020",
			name: "Краткосрочные финансовые обязательства оцениваемые по справедливой стоимости через прибыль или убыток",
			accountType: "liability",
			description: "Краткосрочные финансовые обязательства оцениваемые по справедливой стоимости через прибыль или убыток",
			isActive: true,
		},
		{
			code: "3030",
			name: "Производные финансовые инструменты",
			accountType: "liability",
			description: "Производные финансовые инструменты",
			isActive: true,
		},
		{
			code: "3040",
			name: "Краткосрочная кредиторская задолженность по дивидендам и доходам участников",
			accountType: "liability",
			description: "Краткосрочная кредиторская задолженность по дивидендам и доходам участников",
			isActive: true,
		},
		{
			code: "3050",
			name: "Краткосрочные вознаграждения к выплате",
			accountType: "liability",
			description: "Краткосрочные вознаграждения к выплате",
			isActive: true,
		},
		{
			code: "3060",
			name: "Текущая часть долгосрочных финансовых обязательств оцениваемых по амортизированной стоимости",
			accountType: "liability",
			description: "Текущая часть долгосрочных финансовых обязательств оцениваемых по амортизированной стоимости",
			isActive: true,
		},
		{
			code: "3070",
			name: "Текущая часть долгосрочных финансовых обязательств оцениваемых по справедливой стоимости через прибыль или убытки",
			accountType: "liability",
			description: "Текущая часть долгосрочных финансовых обязательств оцениваемых по справедливой стоимости через прибыль или убытки",
			isActive: true,
		},
		{
			code: "3080",
			name: "Прочие краткосрочные финансовые обязательства",
			accountType: "liability",
			description: "Прочие краткосрочные финансовые обязательства",
			isActive: true,
		},
		{
			code: "3140",
			name: "Акцизы",
			accountType: "liability",
			description: "Акцизы",
			isActive: true,
		},
		{
			code: "3150",
			name: "Социальный налог",
			accountType: "liability",
			description: "Социальный налог",
			isActive: true,
		},
		{
			code: "3160",
			name: "Земельный налог",
			accountType: "liability",
			description: "Земельный налог",
			isActive: true,
		},
		{
			code: "3170",
			name: "Налог на транспортные средства",
			accountType: "liability",
			description: "Налог на транспортные средства",
			isActive: true,
		},
		{
			code: "3180",
			name: "Налог на имущество",
			accountType: "liability",
			description: "Налог на имущество",
			isActive: true,
		},
		{
			code: "3212",
			name: "Обязательства по взносам на социальное медицинское страхование",
			accountType: "liability",
			description: "Обязательства по взносам на социальное медицинское страхование",
			isActive: true,
		},
		{
			code: "3213",
			name: "Обязательства по отчислениям на социальное медицинское страхование",
			accountType: "liability",
			description: "Обязательства по отчислениям на социальное медицинское страхование",
			isActive: true,
		},
		{
			code: "3231",
			name: "Обязательства по единому платежу",
			accountType: "liability",
			description: "Обязательства по единому платежу",
			isActive: true,
		},
		{
			code: "3232",
			name: "Прочие обязательства по другим обязательным платежам",
			accountType: "liability",
			description: "Прочие обязательства по другим обязательным платежам",
			isActive: true,
		},
		{
			code: "3240",
			name: "Прочие обязательства по другим добровольным платежам",
			accountType: "liability",
			description: "Прочие обязательства по другим добровольным платежам",
			isActive: true,
		},
		{
			code: "3320",
			name: "Краткосрочная кредиторская задолженность дочерним организациям",
			accountType: "liability",
			description: "Краткосрочная кредиторская задолженность дочерним организациям",
			isActive: true,
		},
		{
			code: "3330",
			name: "Краткосрочная кредиторская задолженность ассоциированным и совместным организациям",
			accountType: "liability",
			description: "Краткосрочная кредиторская задолженность ассоциированным и совместным организациям",
			isActive: true,
		},
		{
			code: "3340",
			name: "Краткосрочная кредиторская задолженность филиалам и структурным подразделениям",
			accountType: "liability",
			description: "Краткосрочная кредиторская задолженность филиалам и структурным подразделениям",
			isActive: true,
		},
		{
			code: "3360",
			name: "Краткосрочная задолженность по аренде",
			accountType: "liability",
			description: "Краткосрочная задолженность по аренде",
			isActive: true,
		},
		{
			code: "3370",
			name: "Текущая часть долгосрочной кредиторской задолженности",
			accountType: "liability",
			description: "Текущая часть долгосрочной кредиторской задолженности",
			isActive: true,
		},
		{
			code: "3381",
			name: "Задолженность по возвратам реализованных готовой продукции товаров услуг",
			accountType: "liability",
			description: "Задолженность по возвратам реализованных готовой продукции товаров услуг",
			isActive: true,
		},
		{
			code: "3382",
			name: "Задолженность по присужденным штрафам пеням неустойкам",
			accountType: "liability",
			description: "Задолженность по присужденным штрафам пеням неустойкам",
			isActive: true,
		},
		{
			code: "3383",
			name: "Задолженность по ошибочно зачисленным суммам на счетах в банках",
			accountType: "liability",
			description: "Задолженность по ошибочно зачисленным суммам на счетах в банках",
			isActive: true,
		},
		{
			code: "3384",
			name: "Задолженность по депонированной заработной плате",
			accountType: "liability",
			description: "Задолженность по депонированной заработной плате",
			isActive: true,
		},
		{
			code: "3385",
			name: "Задолженность по исполнительным листам",
			accountType: "liability",
			description: "Задолженность по исполнительным листам",
			isActive: true,
		},
		{
			code: "3386",
			name: "Задолженность перед подотчетными лицами",
			accountType: "liability",
			description: "Задолженность перед подотчетными лицами",
			isActive: true,
		},
		{
			code: "3387",
			name: "Прочая краткосрочная кредиторская задолженность",
			accountType: "liability",
			description: "Прочая краткосрочная кредиторская задолженность",
			isActive: true,
		},
		{
			code: "3410",
			name: "Краткосрочные гарантийные обязательства",
			accountType: "liability",
			description: "Краткосрочные гарантийные обязательства",
			isActive: true,
		},
		{
			code: "3420",
			name: "Краткосрочные обязательства по юридическим претензиям",
			accountType: "liability",
			description: "Краткосрочные обязательства по юридическим претензиям",
			isActive: true,
		},
		{
			code: "3430",
			name: "Краткосрочные оценочные обязательства по вознаграждениям работникам",
			accountType: "liability",
			description: "Краткосрочные оценочные обязательства по вознаграждениям работникам",
			isActive: true,
		},
		{
			code: "3440",
			name: "Прочие краткосрочные оценочные обязательства",
			accountType: "liability",
			description: "Прочие краткосрочные оценочные обязательства",
			isActive: true,
		},
		{
			code: "3510",
			name: "Краткосрочные авансы полученные",
			accountType: "liability",
			description: "Краткосрочные авансы полученные",
			isActive: true,
		},
		{
			code: "3520",
			name: "Доходы будущих периодов",
			accountType: "liability",
			description: "Доходы будущих периодов",
			isActive: true,
		},
		{
			code: "3530",
			name: "Обязательства группы на выбытие предназначенной для продажи",
			accountType: "liability",
			description: "Обязательства группы на выбытие предназначенной для продажи",
			isActive: true,
		},
		{
			code: "3540",
			name: "Краткосрочные обязательства по договорам",
			accountType: "liability",
			description: "Краткосрочные обязательства по договорам",
			isActive: true,
		},
		{
			code: "3550",
			name: "Долговой компонент комбинированного краткосрочного финансового инструмента",
			accountType: "liability",
			description: "Долговой компонент комбинированного краткосрочного финансового инструмента",
			isActive: true,
		},
		{
			code: "3560",
			name: "Прочие краткосрочные обязательства",
			accountType: "liability",
			description: "Прочие краткосрочные обязательства",
			isActive: true,
		},
		{
			code: "4020",
			name: "Долгосрочные финансовые обязательства оцениваемые по справедливой стоимости через прибыль или убыток",
			accountType: "liability",
			description: "Долгосрочные финансовые обязательства оцениваемые по справедливой стоимости через прибыль или убыток",
			isActive: true,
		},
		{
			code: "4030",
			name: "Производные финансовые инструменты",
			accountType: "liability",
			description: "Производные финансовые инструменты",
			isActive: true,
		},
		{
			code: "4040",
			name: "Долгосрочная задолженность по дивидендам и доходам участников",
			accountType: "liability",
			description: "Долгосрочная задолженность по дивидендам и доходам участников",
			isActive: true,
		},
		{
			code: "4050",
			name: "Долгосрочные вознаграждения к выплате",
			accountType: "liability",
			description: "Долгосрочные вознаграждения к выплате",
			isActive: true,
		},
		{
			code: "4060",
			name: "Прочие долгосрочные финансовые обязательства",
			accountType: "liability",
			description: "Прочие долгосрочные финансовые обязательства",
			isActive: true,
		},
		{
			code: "4110",
			name: "Долгосрочная кредиторская задолженность поставщикам и подрядчикам",
			accountType: "liability",
			description: "Долгосрочная кредиторская задолженность поставщикам и подрядчикам",
			isActive: true,
		},
		{
			code: "4120",
			name: "Долгосрочная кредиторская задолженность дочерним организациям",
			accountType: "liability",
			description: "Долгосрочная кредиторская задолженность дочерним организациям",
			isActive: true,
		},
		{
			code: "4130",
			name: "Долгосрочная кредиторская задолженность ассоциированным и совместным организациям",
			accountType: "liability",
			description: "Долгосрочная кредиторская задолженность ассоциированным и совместным организациям",
			isActive: true,
		},
		{
			code: "4140",
			name: "Долгосрочная кредиторская задолженность филиалам и структурным подразделениям",
			accountType: "liability",
			description: "Долгосрочная кредиторская задолженность филиалам и структурным подразделениям",
			isActive: true,
		},
		{
			code: "4150",
			name: "Долгосрочная задолженность по аренде",
			accountType: "liability",
			description: "Долгосрочная задолженность по аренде",
			isActive: true,
		},
		{
			code: "4161",
			name: "Долгосрочная задолженность по возвратам реализованных готовой продукции товаров работ услуг",
			accountType: "liability",
			description: "Долгосрочная задолженность по возвратам реализованных готовой продукции товаров работ услуг",
			isActive: true,
		},
		{
			code: "4162",
			name: "Долгосрочная задолженность по присужденным штрафам пеням неустойкам",
			accountType: "liability",
			description: "Долгосрочная задолженность по присужденным штрафам пеням неустойкам",
			isActive: true,
		},
		{
			code: "4163",
			name: "Долгосрочная задолженность по ошибочно зачисленным суммам на счетах в банках",
			accountType: "liability",
			description: "Долгосрочная задолженность по ошибочно зачисленным суммам на счетах в банках",
			isActive: true,
		},
		{
			code: "4164",
			name: "Долгосрочная задолженность по депонированной заработной плате",
			accountType: "liability",
			description: "Долгосрочная задолженность по депонированной заработной плате",
			isActive: true,
		},
		{
			code: "4165",
			name: "Долгосрочная задолженность по исполнительным листам",
			accountType: "liability",
			description: "Долгосрочная задолженность по исполнительным листам",
			isActive: true,
		},
		{
			code: "4166",
			name: "Долгосрочная задолженность перед подотчетными лицами",
			accountType: "liability",
			description: "Долгосрочная задолженность перед подотчетными лицами",
			isActive: true,
		},
		{
			code: "4167",
			name: "Прочая долгосрочная кредиторская задолженность",
			accountType: "liability",
			description: "Прочая долгосрочная кредиторская задолженность",
			isActive: true,
		},
		{
			code: "4210",
			name: "Долгосрочные гарантийные обязательства",
			accountType: "liability",
			description: "Долгосрочные гарантийные обязательства",
			isActive: true,
		},
		{
			code: "4220",
			name: "Долгосрочные оценочные обязательства по юридическим претензиям",
			accountType: "liability",
			description: "Долгосрочные оценочные обязательства по юридическим претензиям",
			isActive: true,
		},
		{
			code: "4230",
			name: "Долгосрочные оценочные обязательства по вознаграждениям работникам",
			accountType: "liability",
			description: "Долгосрочные оценочные обязательства по вознаграждениям работникам",
			isActive: true,
		},
		{
			code: "4240",
			name: "Прочие долгосрочные оценочные обязательства",
			accountType: "liability",
			description: "Прочие долгосрочные оценочные обязательства",
			isActive: true,
		},
		{
			code: "4310",
			name: "Отложенные налоговые обязательства по корпоративному подоходному налогу",
			accountType: "liability",
			description: "Отложенные налоговые обязательства по корпоративному подоходному налогу",
			isActive: true,
		},
		{
			code: "4410",
			name: "Долгосрочные авансы полученные",
			accountType: "liability",
			description: "Долгосрочные авансы полученные",
			isActive: true,
		},
		{
			code: "4420",
			name: "Доходы будущих периодов",
			accountType: "liability",
			description: "Доходы будущих периодов",
			isActive: true,
		},
		{
			code: "4430",
			name: "Долгосрочные обязательства по договорам",
			accountType: "liability",
			description: "Долгосрочные обязательства по договорам",
			isActive: true,
		},
		{
			code: "4440",
			name: "Долговой компонент комбинированного долгосрочного финансового инструмента",
			accountType: "liability",
			description: "Долговой компонент комбинированного долгосрочного финансового инструмента",
			isActive: true,
		},
		{
			code: "4450",
			name: "Прочие долгосрочные обязательства",
			accountType: "liability",
			description: "Прочие долгосрочные обязательства",
			isActive: true,
		},
		{
			code: "5020",
			name: "Простые акции",
			accountType: "equity",
			description: "Простые акции",
			isActive: true,
		},
		{
			code: "5030",
			name: "Вклады и паи",
			accountType: "equity",
			description: "Вклады и паи",
			isActive: true,
		},
		{
			code: "5110",
			name: "Неоплаченный капитал",
			accountType: "equity",
			description: "Неоплаченный капитал",
			isActive: true,
		},
		{
			code: "5210",
			name: "Выкупленные собственные долевые инструменты",
			accountType: "equity",
			description: "Выкупленные собственные долевые инструменты",
			isActive: true,
		},
		{
			code: "5310",
			name: "Эмиссионный доход",
			accountType: "equity",
			description: "Эмиссионный доход",
			isActive: true,
		},
		{
			code: "5410",
			name: "Дополнительно оплаченный капитал по безвозмездным операциям с основной организацией",
			accountType: "equity",
			description: "Дополнительно оплаченный капитал по безвозмездным операциям с основной организацией",
			isActive: true,
		},
		{
			code: "5420",
			name: "Дополнительно оплаченный капитал по прочим операциям",
			accountType: "equity",
			description: "Дополнительно оплаченный капитал по прочим операциям",
			isActive: true,
		},
		{
			code: "5510",
			name: "Резервный капитал установленный учредительными документами",
			accountType: "equity",
			description: "Резервный капитал установленный учредительными документами",
			isActive: true,
		},
		{
			code: "5520",
			name: "Резерв на переоценку основных средств",
			accountType: "equity",
			description: "Резерв на переоценку основных средств",
			isActive: true,
		},
		{
			code: "5530",
			name: "Резерв на переоценку нематериальных активов",
			accountType: "equity",
			description: "Резерв на переоценку нематериальных активов",
			isActive: true,
		},
		{
			code: "5540",
			name: "Резерв на переоценку финансовых активов учитываемых по справедливой стоимости через прочий совокупный доход",
			accountType: "equity",
			description: "Резерв на переоценку финансовых активов учитываемых по справедливой стоимости через прочий совокупный доход",
			isActive: true,
		},
		{
			code: "5550",
			name: "Резерв под убытки по финансовым активам",
			accountType: "equity",
			description: "Резерв под убытки по финансовым активам",
			isActive: true,
		},
		{
			code: "5560",
			name: "Резерв на пересчет иностранной валюты по зарубежной деятельности",
			accountType: "equity",
			description: "Резерв на пересчет иностранной валюты по зарубежной деятельности",
			isActive: true,
		},
		{
			code: "5570",
			name: "Прочие резервы",
			accountType: "equity",
			description: "Прочие резервы",
			isActive: true,
		},
		{
			code: "5710",
			name: "Итоговая прибыль итоговый убыток",
			accountType: "equity",
			description: "Итоговая прибыль итоговый убыток",
			isActive: true,
		},
		{
			code: "6020",
			name: "Возврат проданной продукции",
			accountType: "revenue",
			description: "Возврат проданной продукции",
			isActive: true,
		},
		{
			code: "6030",
			name: "Скидки с цены и продаж",
			accountType: "revenue",
			description: "Скидки с цены и продаж",
			isActive: true,
		},
		{
			code: "6120",
			name: "Доходы по дивидендам",
			accountType: "revenue",
			description: "Доходы по дивидендам",
			isActive: true,
		},
		{
			code: "6130",
			name: "Доходы от финансовой аренды",
			accountType: "revenue",
			description: "Доходы от финансовой аренды",
			isActive: true,
		},
		{
			code: "6140",
			name: "Доходы от операций с инвестициями в недвижимость",
			accountType: "revenue",
			description: "Доходы от операций с инвестициями в недвижимость",
			isActive: true,
		},
		{
			code: "6150",
			name: "Доходы от изменения справедливой стоимости финансовых инструментов",
			accountType: "revenue",
			description: "Доходы от изменения справедливой стоимости финансовых инструментов",
			isActive: true,
		},
		{
			code: "6160",
			name: "Прочие доходы от финансирования",
			accountType: "revenue",
			description: "Прочие доходы от финансирования",
			isActive: true,
		},
		{
			code: "6220",
			name: "Доходы от безвозмездно полученных активов",
			accountType: "revenue",
			description: "Доходы от безвозмездно полученных активов",
			isActive: true,
		},
		{
			code: "6230",
			name: "Доходы от государственных субсидий",
			accountType: "revenue",
			description: "Доходы от государственных субсидий",
			isActive: true,
		},
		{
			code: "6240",
			name: "Доходы от восстановления убытка от обесценения по нефинансовым активам",
			accountType: "revenue",
			description: "Доходы от восстановления убытка от обесценения по нефинансовым активам",
			isActive: true,
		},
		{
			code: "6250",
			name: "Доходы от курсовой разницы",
			accountType: "revenue",
			description: "Доходы от курсовой разницы",
			isActive: true,
		},
		{
			code: "6260",
			name: "Доходы от операционной аренды",
			accountType: "revenue",
			description: "Доходы от операционной аренды",
			isActive: true,
		},
		{
			code: "6270",
			name: "Доходы от изменения справедливой стоимости биологических активов",
			accountType: "revenue",
			description: "Доходы от изменения справедливой стоимости биологических активов",
			isActive: true,
		},
		{
			code: "6280",
			name: "Доходы от восстановления убытка от обесценения по финансовым активам",
			accountType: "revenue",
			description: "Доходы от восстановления убытка от обесценения по финансовым активам",
			isActive: true,
		},
		{
			code: "6310",
			name: "Доходы связанные с прекращаемой деятельностью",
			accountType: "revenue",
			description: "Доходы связанные с прекращаемой деятельностью",
			isActive: true,
		},
		{
			code: "6410",
			name: "Доля прибыли ассоциированных организаций",
			accountType: "revenue",
			description: "Доля прибыли ассоциированных организаций",
			isActive: true,
		},
		{
			code: "6420",
			name: "Доля прибыли совместных организаций",
			accountType: "revenue",
			description: "Доля прибыли совместных организаций",
			isActive: true,
		},
		{
			code: "7320",
			name: "Расходы на выплату процентов по финансовой аренде",
			accountType: "expense",
			description: "Расходы на выплату процентов по финансовой аренде",
			isActive: true,
		},
		{
			code: "7330",
			name: "Расходы от изменения справедливой стоимости финансовых инструментов",
			accountType: "expense",
			description: "Расходы от изменения справедливой стоимости финансовых инструментов",
			isActive: true,
		},
		{
			code: "7340",
			name: "Прочие расходы на финансирование",
			accountType: "expense",
			description: "Прочие расходы на финансирование",
			isActive: true,
		},
		{
			code: "7420",
			name: "Расходы от обесценения нефинансовых активов",
			accountType: "expense",
			description: "Расходы от обесценения нефинансовых активов",
			isActive: true,
		},
		{
			code: "7430",
			name: "Расходы по курсовой разнице",
			accountType: "expense",
			description: "Расходы по курсовой разнице",
			isActive: true,
		},
		{
			code: "7440",
			name: "Расходы по обесценению дебиторской задолженности",
			accountType: "expense",
			description: "Расходы по обесценению дебиторской задолженности",
			isActive: true,
		},
		{
			code: "7450",
			name: "Расходы по операционной аренде",
			accountType: "expense",
			description: "Расходы по операционной аренде",
			isActive: true,
		},
		{
			code: "7460",
			name: "Расходы от изменения справедливой стоимости биологических активов",
			accountType: "expense",
			description: "Расходы от изменения справедливой стоимости биологических активов",
			isActive: true,
		},
		{
			code: "7470",
			name: "Расходы от обесценения финансовых инструментов",
			accountType: "expense",
			description: "Расходы от обесценения финансовых инструментов",
			isActive: true,
		},
		{
			code: "7510",
			name: "Расходы связанные с прекращаемой деятельностью",
			accountType: "expense",
			description: "Расходы связанные с прекращаемой деятельностью",
			isActive: true,
		},
		{
			code: "7610",
			name: "Доля в убытке ассоциированных организаций",
			accountType: "expense",
			description: "Доля в убытке ассоциированных организаций",
			isActive: true,
		},
		{
			code: "7620",
			name: "Доля в убытке совместных организаций",
			accountType: "expense",
			description: "Доля в убытке совместных организаций",
			isActive: true,
		},
		{
			code: "8120",
			name: "Производство из давальческого сырья",
			accountType: "expense",
			description: "Производство из давальческого сырья",
			isActive: true,
		},
		{
			code: "8210",
			name: "Полуфабрикаты собственного производства",
			accountType: "expense",
			description: "Полуфабрикаты собственного производства",
			isActive: true,
		},
		{
			code: "8310",
			name: "Вспомогательные производства",
			accountType: "expense",
			description: "Вспомогательные производства",
			isActive: true,
		},
		{
			code: "8410",
			name: "Накладные расходы",
			accountType: "expense",
			description: "Накладные расходы",
			isActive: true,
		},
		{
			code: "9011",
			name: "Арендованные основные средства",
			accountType: "asset",
			description: "Арендованные основные средства",
			isActive: true,
		},
		{
			code: "9012",
			name: "Амортизация арендованных основных средств",
			accountType: "asset",
			description: "Амортизация арендованных основных средств",
			isActive: true,
		},
		{
			code: "9021",
			name: "Материалы на складе",
			accountType: "asset",
			description: "Материалы на складе",
			isActive: true,
		},
		{
			code: "9022",
			name: "Материалы переданные в производство",
			accountType: "expense",
			description: "Материалы переданные в производство",
			isActive: true,
		},
	];
